parameters:
#    opifer_crud.example.class: Opifer\CrudBundle\Example

services:
    # Router
    opifer.crud.crud_router:
        class: Opifer\CrudBundle\Router\CrudRouter
        arguments: [@service_container, %opifer_crud.route_prefix%]

    opifer.crud.api_router:
        class: Opifer\CrudBundle\Router\ApiRouter
        arguments: [@service_container]

    # Datagrid
    opifer.crud.datagrid_builder:
        class: Opifer\CrudBundle\Datagrid\DatagridBuilder
        arguments: [@service_container]

    opifer.crud.datagrid_factory:
        class: Opifer\CrudBundle\Datagrid\DatagridFactory
        arguments: [@opifer.crud.datagrid_builder]

    opifer.crud.view_builder:
        class: Opifer\CrudBundle\Datagrid\ViewBuilder
        arguments: [@doctrine.orm.entity_manager, @opifer.crud.entity_helper]

    # Form Types
    opifer.crud.crud_type:
        class: Opifer\CrudBundle\Form\Type\CrudType
        arguments: [@opifer.crud.entity_helper, @opifer.crud.form_annotation_reader, %opifer_eav.valueset_class%]
        tags:
            - { name: form.type, alias: crud_form }

    # Helpers
    opifer.crud.entity_helper:
        class: Opifer\CrudBundle\Doctrine\EntityHelper
        arguments: [@doctrine.orm.entity_manager]

    # Managers
    opifer.crud.listview_manager:
        class: Opifer\CrudBundle\Model\ListViewManager
        arguments: [@doctrine.orm.entity_manager, @serializer, @opifer.crud.entity_helper, @form.factory]

    # Transformers
    opifer.crud.slug_transformer:
        class: Opifer\CrudBundle\Transformer\SlugTransformer
        arguments: [%opifer_crud.routes%]

    # AnnotationReader
    opifer.crud.form_annotation_reader:
        class: Opifer\CrudBundle\Annotation\FormAnnotationReader

    # JMS Serializer
    jms_serializer.naming_strategy:
      class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    # Cell types
    opifer.crud.cell_registry:
        class: Opifer\CrudBundle\Datagrid\Cell\CellRegistry

    # Field Types
    opifer.crud.form.collapsible_collection:
        class: Opifer\CrudBundle\Form\Type\CollapsibleCollectionType
        tags:
            - { name: form.type, alias: collapsible_collection }

    # Managers
    opifer.crud.relation_manager:
        class: Opifer\CrudBundle\Manager\RelationManager
        arguments: [@doctrine.orm.entity_manager, @opifer.crud.entity_helper]

    opifer.crud.export_manager:
        class: Opifer\CrudBundle\Manager\ExportManager
        arguments: [@serializer, @phpexcel]