language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_DEPRECATIONS_HELPER=weak

before_install: composer selfupdate

install: composer update --prefer-dist --no-interaction

script: phpunit --coverage-text

branches:
  only:
    - master
    - develop
